# build packages
FROM node:10.16-alpine AS node_modules

WORKDIR /tmp
RUN apk add --no-cache --update krb5-dev alpine-sdk python tini
# RUN apk add --no-cache --update tini
ENTRYPOINT ["/sbin/tini", "--"]

WORKDIR /app
COPY . .
RUN npm install

CMD ["npm", "start"]
