version: '3'
services:
  todo_web:
    build: .
    restart: always
    container_name: todo_webserver
    volumes:
      - .:/app
    depends_on:
      - todo_database
    environment:
      DJANGO_SETTINGS_MODULE: todo.settings
      PYTHONPATH: /app
  todo_database:
    image: postgres:12-alpine
    container_name: todo_database
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
      POSTGRES_USER: todo_admin
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "15432:5432"
  frontend:
    container_name: frontend
    image: nginx:latest
    ports:
      - "28000:80"
    volumes:
      - .:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - todo_web
