version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplesecret
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
  api:
    build: ./api
    # volumes:
    #   - ./api:/app
    ports:
      - 3000:80
    command: ./wait-for db:5432 -- npm run start.dev
