version: "3"

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
      - mysql
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mysql
    expose:
      - 8080
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=todo_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"